### ISSUE TITLE
Can we move the editor to the gh-pages?

### ISSUE THREAD

**Issue by theonlygusti** [Bloxport/Bloxport_Editor#3]
Can we work on the editor in the github pages `bloxport.github.io` repository?

I don't see the point of having two repositories for this.

**Comment by C0deAMet** [comment]
if we create the editor here, we can trial and error it, and once it's finished we can add it to the GHPages repos

**Comment by theonlygusti** [comment]
Or we can work in a separate branch of the gh-pages repo, as is standard practice.

**Comment by theonlygusti** [comment]
We make our changes to a branch of the gh-pages repo, and only push our changes to the production branch once they're ready. This is how github development should work.

**Comment by C0deAMet** [comment]
how will we test it though?

**Comment by C0deAMet** [comment]
Also this is where other can access and edit the editor, this is where the editor will be, sorry we cant move it

**Comment by theonlygusti** [comment]
I feel like it should be moved.

**Comment by theonlygusti** [comment]
Ok I still feel strongly that it makes more sense to work in the other repo, so I'm reopening

**Comment by an-OK-squirrel** [comment]
I agree with gusti here. You should *at least* be running the github.io repo *as a fork* of the other one so you can pull the history?

**Comment by an-OK-squirrel** [comment]
>how will we test it though?

by changing the branch and running your local copy in the browser???
out of interest have you ever used git before?

**Comment by theonlygusti** [comment]
lol I can't believe you closed this. That's pathetic, why don't you listen to all the programmers here with far more experience than you?
