### ISSUE TITLE
Do we want to use the unlicense instead of the MIT license? 

### ISSUE THREAD

**Issue by theonlygusti** [Bloxport/Bloxport_Editor#8]

**Comment by card100** [comment]
Why would we want that?

**Comment by theonlygusti** [comment]
To have no obligations on our part. Rather than worrying about getting into lawsuits and copyright claims, we can focus on developing.

**Comment by C0deAMet** [comment]
maybe we could have it unlicensed for now, then we can add a licence after we have finished developing?

**Comment by theonlygusti** [comment]
Omfg

@C0deAMet  are you serious?

The unlicense is a license. A valid license.

**Comment by C0deAMet** [comment]
sorry I meant to say change the licence
